# Generated by Django 2.1 on 2018-08-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars_app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacians',
            name='city',
            field=models.CharField(default='NULL', max_length=25),
        ),
        migrations.AddField(
            model_name='spacians',
            name='mobile_no',
            field=models.CharField(default='NULL', max_length=10),
        ),
        migrations.AddField(
            model_name='spacians',
            name='state',
            field=models.CharField(default='NULL', max_length=20),
        ),
    ]
