# Generated by Django 2.1 on 2018-08-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars_app1', '0002_auto_20180816_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacians',
            name='city',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='spacians',
            name='mobile_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='spacians',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
    ]
